context:
  name: codex
  version: "0.1.2504301751"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@openai/codex/-/codex-${{ version }}.tgz
  sha256: 534efae4ced56e98b136a13bee4523acebf261267fecc11ea3df9a2854875186

build:
  number: 0
  noarch: generic


requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - third-party-licenses.txt
    - LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
